/// Flutter icons RickMorty
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RickMorty
///      fonts:
///       - asset: fonts/RickMorty.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RickMorty {
  RickMorty._();

  static const _kFontFam = 'RickMorty';
  static const String? _kFontPkg = null;

  static const IconData list = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planet = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_close = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_palette = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_up = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_down = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
